/* MediStore ERP demo. Data is stored in this browser with localStorage. */
const seed={medicines:[
 {id:'MED-001',name:'Dolo 650',generic:'Paracetamol',category:'Analgesic',unit:'Tablet',reorder:30,price:2.5,batches:[{id:'BT-101',qty:120,expiry:'2027-03-31',cost:1.4}]},
 {id:'MED-002',name:'Augmentin 625 Duo',generic:'Amoxicillin + Clavulanate',category:'Antibiotic',unit:'Tablet',reorder:20,price:18,batches:[{id:'BT-112',qty:42,expiry:'2026-11-30',cost:13.2}]},
 {id:'MED-003',name:'Cetirizine 10mg',generic:'Cetirizine',category:'Antihistamine',unit:'Tablet',reorder:25,price:1.8,batches:[{id:'BT-087',qty:18,expiry:'2027-01-31',cost:0.8}]},
 {id:'MED-004',name:'Azithral 500',generic:'Azithromycin',category:'Antibiotic',unit:'Tablet',reorder:15,price:11.5,batches:[{id:'BT-095',qty:65,expiry:'2026-10-31',cost:8.3}]},
 {id:'MED-005',name:'Pan-D',generic:'Pantoprazole + Domperidone',category:'Gastro',unit:'Capsule',reorder:20,price:12,batches:[{id:'BT-109',qty:9,expiry:'2026-12-31',cost:8.1}]},
 {id:'MED-006',name:'ORS Orange',generic:'Oral Rehydration Salts',category:'Electrolyte',unit:'Sachet',reorder:12,price:21,batches:[{id:'BT-076',qty:36,expiry:'2027-06-30',cost:15}]},
 {id:'MED-007',name:'Volini Gel 30g',generic:'Diclofenac topical',category:'Topical',unit:'Tube',reorder:10,price:95,batches:[{id:'BT-121',qty:14,expiry:'2027-04-30',cost:68}]},
 {id:'MED-008',name:'Vitamin C 500',generic:'Ascorbic Acid',category:'Supplement',unit:'Tablet',reorder:25,price:4, batches:[{id:'BT-134',qty:90,expiry:'2027-08-31',cost:2.2}]},
 {id:'MED-009',name:'Metformin 500',generic:'Metformin Hydrochloride',category:'Diabetes',unit:'Tablet',reorder:20,price:3, batches:[{id:'BT-137',qty:52,expiry:'2026-09-30',cost:1.4}]},
 {id:'MED-010',name:'Crocin Advance 500',generic:'Paracetamol',category:'Analgesic',unit:'Tablet',reorder:25,price:2.2,batches:[{id:'BT-141',qty:84,expiry:'2027-02-28',cost:1.2}]},
 {id:'MED-011',name:'Combiflam',generic:'Ibuprofen + Paracetamol',category:'Analgesic',unit:'Tablet',reorder:20,price:3.5,batches:[{id:'BT-142',qty:48,expiry:'2027-05-31',cost:2.1}]},
 {id:'MED-012',name:'Sinarest New',generic:'Paracetamol + Phenylephrine + Chlorpheniramine',category:'Cold & Flu',unit:'Tablet',reorder:15,price:4.5,batches:[{id:'BT-143',qty:32,expiry:'2027-01-31',cost:2.8}]},
 {id:'MED-013',name:'Allegra 120',generic:'Fexofenadine',category:'Antihistamine',unit:'Tablet',reorder:12,price:13,batches:[{id:'BT-144',qty:27,expiry:'2027-07-31',cost:9.4}]},
 {id:'MED-014',name:'Pantocid 40',generic:'Pantoprazole',category:'Gastro',unit:'Tablet',reorder:20,price:9.5,batches:[{id:'BT-145',qty:56,expiry:'2027-03-31',cost:6.3}]},
 {id:'MED-015',name:'Omez 20',generic:'Omeprazole',category:'Gastro',unit:'Capsule',reorder:15,price:5.5,batches:[{id:'BT-146',qty:43,expiry:'2027-04-30',cost:3.6}]},
 {id:'MED-016',name:'Glycomet GP 1',generic:'Glimepiride + Metformin',category:'Diabetes',unit:'Tablet',reorder:12,price:8,batches:[{id:'BT-147',qty:29,expiry:'2027-06-30',cost:5.1}]},
 {id:'MED-017',name:'Telma 40',generic:'Telmisartan',category:'Cardiac',unit:'Tablet',reorder:15,price:10.5,batches:[{id:'BT-148',qty:38,expiry:'2027-08-31',cost:7.2}]},
 {id:'MED-018',name:'Amlong 5',generic:'Amlodipine',category:'Cardiac',unit:'Tablet',reorder:15,price:6,batches:[{id:'BT-149',qty:41,expiry:'2027-05-31',cost:3.9}]},
 {id:'MED-019',name:'Shelcal 500',generic:'Calcium + Vitamin D3',category:'Supplement',unit:'Tablet',reorder:20,price:7,batches:[{id:'BT-150',qty:67,expiry:'2027-10-31',cost:4.4}]},
 {id:'MED-020',name:'Becosules',generic:'B-Complex + Vitamin C',category:'Supplement',unit:'Capsule',reorder:15,price:4.2,batches:[{id:'BT-151',qty:58,expiry:'2027-09-30',cost:2.7}]},
 {id:'MED-021',name:'Benadryl Cough Syrup 100ml',generic:'Diphenhydramine combination',category:'Cold & Flu',unit:'Bottle',reorder:10,price:125,batches:[{id:'BT-152',qty:11,expiry:'2027-02-28',cost:88}]},
 {id:'MED-022',name:'Electral ORS 21g',generic:'Oral Rehydration Salts',category:'Electrolyte',unit:'Sachet',reorder:20,price:22,batches:[{id:'BT-153',qty:73,expiry:'2027-11-30',cost:15.5}]},
 {id:'MED-023',name:'Betadine Ointment 15g',generic:'Povidone-Iodine',category:'Antiseptic',unit:'Tube',reorder:8,price:68,batches:[{id:'BT-154',qty:19,expiry:'2027-04-30',cost:47}]},
 {id:'MED-024',name:'Ciplox Eye Drops 5ml',generic:'Ciprofloxacin',category:'Eye Care',unit:'Bottle',reorder:8,price:22,batches:[{id:'BT-155',qty:16,expiry:'2027-01-31',cost:14.8}]},
 {id:'MED-025',name:'Mupirocin Ointment 5g',generic:'Mupirocin',category:'Topical',unit:'Tube',reorder:6,price:92,batches:[{id:'BT-156',qty:8,expiry:'2027-07-31',cost:64}]},
 {id:'MED-026',name:'Amoxyclav 625',generic:'Amoxicillin + Clavulanate',category:'Antibiotic',unit:'Tablet',reorder:15,price:16.5,batches:[{id:'BT-157',qty:25,expiry:'2027-02-28',cost:12.1}]},
 {id:'MED-027',name:'Montair LC',generic:'Montelukast + Levocetirizine',category:'Antihistamine',unit:'Tablet',reorder:12,price:9.5,batches:[{id:'BT-158',qty:34,expiry:'2027-06-30',cost:6.4}]},
 {id:'MED-028',name:'ORS Lemon 21g',generic:'Oral Rehydration Salts',category:'Electrolyte',unit:'Sachet',reorder:15,price:20,batches:[{id:'BT-159',qty:6,expiry:'2026-12-31',cost:14}]},
 {id:'MED-029',name:'Insulin Glargine 100 IU/ml',generic:'Insulin Glargine',category:'Diabetes',unit:'Injection',reorder:5,price:650,batches:[{id:'BT-160',qty:4,expiry:'2026-12-31',cost:520}]},
 {id:'MED-030',name:'Dextromethorphan Syrup 100ml',generic:'Dextromethorphan',category:'Cold & Flu',unit:'Bottle',reorder:8,price:86,batches:[{id:'BT-161',qty:13,expiry:'2027-03-31',cost:58}]}
],suppliers:[{id:'SUP-01',name:'Wellness Pharma Distributors',contact:'Anil Sharma',phone:'+91 98765 43210',email:'orders@wellnesspharma.in',city:'Nagpur',due:12450},{id:'SUP-02',name:'Apollo MedSupply',contact:'Priya Nair',phone:'+91 98220 11223',email:'sales@apollomedsupply.in',city:'Pune',due:6800},{id:'SUP-03',name:'HealthFirst Wholesale',contact:'Rakesh Patel',phone:'+91 97654 87654',email:'care@healthfirst.in',city:'Nagpur',due:0}],sales:[{id:'INV-1048',date:new Date(Date.now()-86400000).toISOString(),customer:'Walk-in customer',items:[{medicineId:'MED-001',name:'Dolo 650',qty:10,price:2.5},{medicineId:'MED-003',name:'Cetirizine 10mg',qty:5,price:1.8}],total:34},{id:'INV-1047',date:new Date(Date.now()-2*86400000).toISOString(),customer:'Walk-in customer',items:[{medicineId:'MED-006',name:'ORS Orange',qty:2,price:21}],total:42}],purchases:[{id:'PO-208',date:new Date(Date.now()-5*86400000).toISOString(),supplier:'Wellness Pharma Distributors',items:4,total:18450,status:'Received'},{id:'PO-207',date:new Date(Date.now()-9*86400000).toISOString(),supplier:'Apollo MedSupply',items:2,total:9800,status:'Received'}],users:[{name:'Keshav Deshpande',email:'admin@medistore.local',role:'Admin',status:'Active'},{name:'Meera Joshi',email:'meera@greencross.in',role:'Pharmacist',status:'Active'},{name:'Rahul Patil',email:'rahul@greencross.in',role:'Cashier',status:'Active'}],role:'Admin'};
let db=loadDb(),page='dashboard',cart=[],query='',invFilter='All';
function loadDb(){try{let saved=JSON.parse(localStorage.getItem('medistore-db'));if(!saved)return structuredClone(seed);let ids=new Set(saved.medicines.map(m=>m.id));for(const m of seed.medicines)if(!ids.has(m.id))saved.medicines.push(structuredClone(m));return saved}catch{return structuredClone(seed)}}
function save(){localStorage.setItem('medistore-db',JSON.stringify(db))}
function money(n){return '₹'+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function num(n){return Number(n||0).toLocaleString('en-IN')}
function stock(m){return m.batches.reduce((s,b)=>s+Number(b.qty),0)}
function nearExpiry(m){const now=new Date();return m.batches.some(b=>{let d=new Date(b.expiry+'T00:00:00');return d>=now&&d<new Date(now.getTime()+91*864e5)&&b.qty>0})}
function dateFmt(d){return new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(s,error=false){let n=document.createElement('div');n.className='toast'+(error?' error':'');n.textContent=s;document.querySelector('#toasts').append(n);setTimeout(()=>n.remove(),2800)}
function setPage(p){page=p;document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===p));document.querySelector('#crumb').textContent=({dashboard:'Overview',billing:'New sale',inventory:'Inventory',purchases:'Purchases',suppliers:'Suppliers',reports:'Reports',medicines:'Medicine catalogue',users:'Team & access'})[p];render()}
function head(title,sub,buttons=''){return `<div class="page-heading"><div><div class="eyebrow">MONDAY, ${dateFmt(new Date())}</div><h1>${title}</h1><div class="subheading">${sub}</div></div><div class="actions">${buttons}</div></div>`}
function btn(label,cls='btn',action='',icon=''){return `<button class="${cls}" ${action?`data-action="${action}"`:''}>${icon}${label}</button>`}
function stats(items){return `<div class="stats">${items.map(i=>`<div class="card stat"><div class="stat-top">${i.label}<span class="stat-icon">${i.icon}</span></div><div class="stat-value">${i.value}</div><div class="stat-foot">${i.foot}</div></div>`).join('')}</div>`}
function productCell(m){return `<div class="product-cell"><div class="product-icon">✚</div><div class="product-meta"><b>${esc(m.name)}</b><small>${esc(m.generic)} · ${esc(m.id)}</small></div></div>`}
function inventoryRows(list=db.medicines){return list.map(m=>{let q=stock(m),status=q===0?'Out of stock':q<=m.reorder?'Low stock':'In stock';return `<tr><td>${productCell(m)}</td><td>${esc(m.category)}</td><td>${num(q)} ${esc(m.unit.toLowerCase())}s</td><td>${m.batches.length?dateFmt(m.batches.sort((a,b)=>a.expiry.localeCompare(b.expiry))[0].expiry):'—'}</td><td>${money(m.price)}</td><td><span class="pill ${status==='In stock'?'green':status==='Low stock'?'amber':'red'}">${status}</span></td><td><button class="text-link" data-action="edit-med" data-id="${m.id}">Edit</button></td></tr>`}).join('')}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${headers.length}" class="empty">No records found.</td></tr>`}</tbody></table></div>`}
function chart(){let vals=[8,11,10,14,12,18,16,22,19,24,21,29,26,34,31,39,36,44,41,48,45,52,50,58,55,64,60,71];let pts=vals.map((v,i)=>`${30+i*25},${165-v*1.8}`).join(' ');let area=`30,165 ${pts} 705,165`;return `<div class="chart-wrap"><svg viewBox="0 0 730 190" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#3c9a70" stop-opacity=".19"/><stop offset="1" stop-color="#3c9a70" stop-opacity="0"/></linearGradient></defs>${[30,70,110,150].map(y=>`<line class="chart-grid" x1="30" y1="${y}" x2="705" y2="${y}"/>`).join('')}<polygon class="chart-area" points="${area}"/><polyline class="chart-line" points="${pts}"/><text class="chart-label" x="30" y="185">01 Sep</text><text class="chart-label" x="225" y="185">08 Sep</text><text class="chart-label" x="420" y="185">15 Sep</text><text class="chart-label" x="620" y="185">22 Sep</text></svg></div>`}
function dashboard(){let low=db.medicines.filter(m=>stock(m)<=m.reorder),exp=db.medicines.filter(nearExpiry),monthSales=db.sales.reduce((s,x)=>s+x.total,0);return `${head('Good morning, Keshav 👋','Here’s what’s happening at your store today.',btn('Export report','btn','export-report','↓ ')+btn('New sale','btn primary','go-billing','＋ '))}${stats([{label:'Sales today',value:money(monthSales),icon:'↗',foot:`<span class="up">↑ 12.8%</span> &nbsp;vs. yesterday`},{label:'Orders today',value:db.sales.length,icon:'▤',foot:`<span class="up">↑ 3</span> &nbsp;transactions recorded`},{label:'Medicine products',value:db.medicines.length,icon:'✚',foot:`Across ${db.medicines.reduce((a,m)=>a+m.batches.length,0)} active batches`},{label:'Needs attention',value:low.length+exp.length,icon:'⚑',foot:`<span class="warn">${low.length} low stock</span> · ${exp.length} expiring soon`}])}<div class="dashboard-grid"><section class="card panel"><div class="panel-head"><div><div class="panel-title">Sales overview</div><div class="panel-note">Daily revenue · September 2026</div></div><div class="chart-key"><span class="legend-dot"></span>Revenue</div></div>${chart()}</section><section class="card panel"><div class="panel-head"><div><div class="panel-title">Inventory alerts</div><div class="panel-note">Items that may need your attention</div></div><button class="text-link" data-action="go-inventory">View inventory →</button></div><div class="alert-list">${[...low.map(m=>({m,type:'low'})),...exp.map(m=>({m,type:'exp'}))].slice(0,4).map(({m,type})=>`<div class="alert-row"><div class="alert-symbol ${type==='low'?'red-bg':'amber-bg'}">${type==='low'?'!':'◷'}</div><div class="alert-copy"><b>${esc(m.name)}</b><small>${type==='low'?`${stock(m)} units left · reorder at ${m.reorder}`:`Batch ${m.batches[0].id} · expiring soon`}</small></div><span class="pill ${type==='low'?'red':'amber'}">${type==='low'?'Low stock':'Expiry soon'}</span></div>`).join('')||'<div class="empty">All clear — no inventory alerts.</div>'}</div></section></div><section class="card table-panel"><div class="panel-head"><div><div class="panel-title">Recent sales</div><div class="panel-note">Latest transactions from your store</div></div><button class="text-link" data-action="go-reports">View all sales →</button></div>${table(['INVOICE','CUSTOMER','ITEMS','DATE','TOTAL','STATUS'],db.sales.slice(0,5).map(s=>`<tr><td><strong>${s.id}</strong></td><td>${esc(s.customer)}</td><td>${s.items.length} products</td><td>${dateFmt(s.date)}</td><td><strong>${money(s.total)}</strong></td><td><span class="pill green">Completed</span></td></tr>`).join(''))}</section><div class="footer-note">MediStore ERP · Store operations made simple</div>`}
function inventoryPage(){let list=db.medicines.filter(m=>{let st=stock(m)<=m.reorder?'Low stock':nearExpiry(m)?'Expiring soon':'In stock';return (invFilter==='All'||st===invFilter)&&(`${m.name} ${m.generic} ${m.category}`.toLowerCase().includes(query.toLowerCase()))});return `${head('Inventory','Track batch quantities, expiry dates and stock value.',btn('Add medicine','btn primary','add-med','＋ '))}<section class="card section-card"><div class="toolbar"><div class="toolbar-left"><input class="search" id="invSearch" placeholder="⌕  Search medicines..." value="${esc(query)}"><select class="select" id="invFilter"><option>All</option><option ${invFilter==='In stock'?'selected':''}>In stock</option><option ${invFilter==='Low stock'?'selected':''}>Low stock</option><option ${invFilter==='Expiring soon'?'selected':''}>Expiring soon</option></select></div><div class="toolbar-right"><span class="subheading">${list.length} products</span></div></div></section><section class="card table-panel">${table(['MEDICINE','CATEGORY','ON HAND','NEXT EXPIRY','SELL PRICE','STATUS',''],inventoryRows(list))}</section>`}
function medicinesPage(){return `${head('Medicine catalogue','Manage medicine names, categories, pricing and reorder levels.',btn('Add medicine','btn primary','add-med','＋ '))}<section class="card section-card"><div class="toolbar"><input class="search" id="invSearch" placeholder="⌕  Search catalogue..." value="${esc(query)}"><span class="subheading">${db.medicines.length} medicines</span></div></section><section class="card table-panel">${table(['MEDICINE','GENERIC NAME','CATEGORY','UNIT','SELL PRICE','REORDER LEVEL',''],db.medicines.filter(m=>`${m.name} ${m.generic}`.toLowerCase().includes(query.toLowerCase())).map(m=>`<tr><td>${productCell(m)}</td><td>${esc(m.generic)}</td><td>${esc(m.category)}</td><td>${esc(m.unit)}</td><td>${money(m.price)}</td><td>${m.reorder}</td><td><button class="text-link" data-action="edit-med" data-id="${m.id}">Edit</button></td></tr>`).join(''))}</section>`}
function billingPage(){let matches=db.medicines.filter(m=>`${m.name} ${m.generic} ${m.id}`.toLowerCase().includes(query.toLowerCase())&&query.length>0);let subtotal=cart.reduce((s,x)=>s+x.qty*x.price,0),disc=Number(document.querySelector('#discount')?.value||0);return `${head('New sale','Type a product name or generic name to add it to the bill.',btn('Clear bill','btn','clear-cart'))}<div class="billing-layout"><div><div class="bill-search"><span class="search-icon">⌕</span><input id="productSearch" placeholder="Search by product name, generic or medicine ID..." value="${esc(query)}" autocomplete="off"><div class="suggestions" id="suggestions" ${matches.length?'':'hidden'}>${matches.map(m=>`<button class="suggestion" data-action="add-cart" data-id="${m.id}"><span><b>${esc(m.name)}</b><small>${esc(m.generic)} · ${stock(m)} ${esc(m.unit.toLowerCase())}s available</small></span><strong>${money(m.price)}</strong></button>`).join('')|| (query?'<div class="empty">No matching medicines. Add it to the catalogue first.</div>':'')}</div></div><section class="card table-panel bill-cart">${cart.length?cart.map((x,i)=>`<div class="line-item"><div><b>${esc(x.name)}</b><small>${money(x.price)} per unit · ${esc(x.batchId||'')}</small></div><div><input aria-label="Quantity" type="number" min="1" max="${stock(db.medicines.find(m=>m.id===x.medicineId))}" value="${x.qty}" data-qty="${i}"></div><b>${money(x.qty*x.price)}</b><button class="remove-line" data-action="remove-cart" data-index="${i}">×</button></div>`).join(''):`<div class="cart-empty"><div><span>▤</span>Start typing to find a medicine.<br>Choose a suggestion to add it to this sale.</div></div>`}</section><p class="subheading">Stock is deducted from the nearest-expiry batch first (FEFO).</p></div><aside class="card invoice-card"><h3>Sale summary</h3><div class="invoice-sub">${cart.length} product line${cart.length===1?'':'s'} · ${new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</div><div class="invoice-field"><label>Customer name <span style="color:#9aa59e">(optional)</span></label><input id="customer" placeholder="Walk-in customer"></div><div class="invoice-line"><span>Subtotal</span><span>${money(subtotal)}</span></div><div class="invoice-field"><label>Discount (₹)</label><input id="discount" type="number" min="0" value="${disc}" placeholder="0"></div><div class="invoice-line total"><span>Total due</span><span>${money(Math.max(0,subtotal-disc))}</span></div><button class="btn primary" data-action="complete-sale" ${cart.length?'':'disabled'}>Complete sale &nbsp;→</button><button class="btn" data-action="print-bill" ${cart.length?'':'disabled'}>Print bill</button></aside></div>`}
function suppliersPage(){return `${head('Suppliers','Keep supplier contacts and outstanding balances in one place.',btn('Add supplier','btn primary','add-supplier','＋ '))}${stats([{label:'Active suppliers',value:db.suppliers.length,icon:'♧',foot:'Available for purchase orders'},{label:'Outstanding balance',value:money(db.suppliers.reduce((s,x)=>s+x.due,0)),icon:'₹',foot:'Across all suppliers'},{label:'Purchase orders',value:db.purchases.length,icon:'⇩',foot:'Recorded in this workspace'},{label:'This month',value:db.purchases.filter(x=>new Date(x.date).getMonth()===new Date().getMonth()).length,icon:'◷',foot:'Purchases received'}])}<section class="card table-panel">${table(['SUPPLIER','CONTACT','PHONE','CITY','BALANCE DUE',''],db.suppliers.map(s=>`<tr><td><strong>${esc(s.name)}</strong><div class="product-meta"><small>${esc(s.email)}</small></div></td><td>${esc(s.contact)}</td><td>${esc(s.phone)}</td><td>${esc(s.city)}</td><td><strong>${money(s.due)}</strong></td><td><button class="text-link" data-action="new-purchase" data-id="${s.id}">＋ Purchase</button></td></tr>`).join(''))}</section>`}
function purchasesPage(){return `${head('Purchases','Record incoming stock and keep your batch quantities accurate.',btn('New purchase','btn primary','new-purchase','＋ '))}${stats([{label:'Total orders',value:db.purchases.length,icon:'⇩',foot:'Purchase records'},{label:'Received',value:db.purchases.filter(p=>p.status==='Received').length,icon:'✓',foot:'Stock added to inventory'},{label:'Total purchase value',value:money(db.purchases.reduce((a,p)=>a+p.total,0)),icon:'₹',foot:'Recorded purchases'},{label:'Suppliers',value:db.suppliers.length,icon:'♧',foot:'In your supplier list'}])}<section class="card table-panel">${table(['ORDER ID','SUPPLIER','ITEMS','ORDER DATE','TOTAL','STATUS'],db.purchases.map(p=>`<tr><td><strong>${p.id}</strong></td><td>${esc(p.supplier)}</td><td>${p.items} products</td><td>${dateFmt(p.date)}</td><td><strong>${money(p.total)}</strong></td><td><span class="pill green">${p.status}</span></td></tr>`).join(''))}</section>`}
function reportsPage(){return `${head('Reports','Review store performance and export operational data.',btn('Export CSV','btn primary','export-report','↓ '))}<div class="toolbar"><div class="toolbar-left"><select class="select" id="reportPeriod"><option>This month</option><option>Last 30 days</option><option>All time</option></select></div></div><div class="report-cards">${[['Sales revenue',money(db.sales.reduce((a,s)=>a+s.total,0))],['Transactions',db.sales.length],['Units in stock',num(db.medicines.reduce((a,m)=>a+stock(m),0))],['Purchase value',money(db.purchases.reduce((a,p)=>a+p.total,0))],['Low stock items',db.medicines.filter(m=>stock(m)<=m.reorder).length],['Suppliers',db.suppliers.length]].map(x=>`<div class="card report-card"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}</div><section class="card table-panel"><div class="panel-head"><div><div class="panel-title">Sales transactions</div><div class="panel-note">Completed bills and payment totals</div></div></div>${table(['INVOICE','DATE','CUSTOMER','LINE ITEMS','TOTAL'],db.sales.map(s=>`<tr><td><strong>${s.id}</strong></td><td>${dateFmt(s.date)}</td><td>${esc(s.customer)}</td><td>${s.items.length}</td><td><strong>${money(s.total)}</strong></td></tr>`).join(''))}</section>`}
function usersPage(){return `${head('Team & access','Manage store users and their role-based access.',btn('Add team member','btn primary','add-user','＋ '))}<section class="card table-panel">${table(['TEAM MEMBER','EMAIL','ROLE','ACCESS'],db.users.map((u,i)=>`<tr><td><div class="product-cell"><span class="avatar">${u.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><strong>${esc(u.name)}</strong></div></td><td>${esc(u.email)}</td><td><select class="role-select" data-role="${i}" ${i===0?'disabled':''}>${['Admin','Pharmacist','Cashier'].map(r=>`<option ${u.role===r?'selected':''}>${r}</option>`).join('')}</select></td><td><span class="pill green">${u.status}</span></td></tr>`).join(''))}</section><div class="card section-card" style="margin-top:14px"><div class="panel-title">Role permissions</div><p class="subheading"><b>Admin</b> — full access, including users and reports. &nbsp; <b>Pharmacist</b> — medicines, inventory, purchases and sales. &nbsp; <b>Cashier</b> — create sales and view product availability.</p></div>`}
function render(){let f={dashboard,billing:billingPage,inventory:inventoryPage,medicines:medicinesPage,suppliers:suppliersPage,purchases:purchasesPage,reports:reportsPage,users:usersPage};document.querySelector('#content').innerHTML=(f[page]||dashboard)();bindDynamic()}
function modal(title,body,submit='Save',onSubmit=''){document.querySelector('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${title}</h2><button class="modal-close" data-action="close-modal">×</button></div><form id="modalForm"><div class="modal-body">${body}</div><div class="modal-foot"><button type="button" class="btn" data-action="close-modal">Cancel</button><button class="btn primary" type="submit">${submit}</button></div></form></div></div>`;document.querySelector('#modalForm').onsubmit=e=>{e.preventDefault();onSubmit&&onSubmit(new FormData(e.currentTarget));closeModal()}}
function closeModal(){document.querySelector('#modalRoot').innerHTML=''}
function medModal(id){let m=db.medicines.find(x=>x.id===id);modal(m?'Edit medicine':'Add medicine',`<div class="form-grid"><div class="field"><label>Medicine name *</label><input name="name" required value="${esc(m?.name||'')}"></div><div class="field"><label>Generic name *</label><input name="generic" required value="${esc(m?.generic||'')}"></div><div class="field"><label>Category</label><input name="category" value="${esc(m?.category||'General')}"></div><div class="field"><label>Unit</label><select name="unit">${['Tablet','Capsule','Syrup','Bottle','Tube','Sachet','Strip','Injection'].map(u=>`<option ${m?.unit===u?'selected':''}>${u}</option>`).join('')}</select></div><div class="field"><label>Sell price (₹) *</label><input name="price" type="number" min="0" step=".01" required value="${m?.price||''}"></div><div class="field"><label>Reorder level</label><input name="reorder" type="number" min="0" value="${m?.reorder||10}"></div>${m?'':`<div class="field"><label>Opening quantity</label><input name="qty" type="number" min="0" value="0"></div><div class="field"><label>Batch expiry</label><input name="expiry" type="date"></div>`}</div>`,m?'Save changes':'Add medicine',fd=>{let v=Object.fromEntries(fd);if(m){Object.assign(m,{name:v.name,generic:v.generic,category:v.category,unit:v.unit,price:Number(v.price),reorder:Number(v.reorder)})}else{let id='MED-'+String(Date.now()).slice(-5);let batches=Number(v.qty)>0?[{id:'BT-'+String(Date.now()).slice(-3),qty:Number(v.qty),expiry:v.expiry||'2027-12-31',cost:Number(v.price)*.65}]:[];db.medicines.push({id,name:v.name,generic:v.generic,category:v.category,unit:v.unit,price:Number(v.price),reorder:Number(v.reorder),batches})}save();toast(m?'Medicine updated':'Medicine added');render()})}
function supplierModal(){modal('Add supplier',`<div class="form-grid"><div class="field"><label>Business name *</label><input name="name" required></div><div class="field"><label>Contact person</label><input name="contact"></div><div class="field"><label>Phone</label><input name="phone"></div><div class="field"><label>Email</label><input name="email" type="email"></div><div class="field"><label>City</label><input name="city"></div><div class="field"><label>Opening balance (₹)</label><input name="due" type="number" value="0"></div></div>`, 'Add supplier',fd=>{let v=Object.fromEntries(fd);db.suppliers.push({id:'SUP-'+String(Date.now()).slice(-4),...v,due:Number(v.due||0)});save();toast('Supplier added');render()})}
function purchaseModal(supplierId){if(!db.suppliers.length)return toast('Add a supplier first.',true);let options=db.suppliers.map(s=>`<option value="${s.id}" ${supplierId===s.id?'selected':''}>${esc(s.name)}</option>`).join('');let medOptions=db.medicines.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('');modal('Record purchase',`<div class="form-grid"><div class="field full"><label>Supplier *</label><select name="supplier" required>${options}</select></div><div class="field full"><label>Medicine *</label><select name="medicine" required>${medOptions}</select></div><div class="field"><label>Batch number</label><input name="batch" placeholder="e.g. BT-205"></div><div class="field"><label>Quantity *</label><input name="qty" type="number" min="1" required value="10"></div><div class="field"><label>Expiry date *</label><input name="expiry" type="date" required></div><div class="field"><label>Cost per unit (₹) *</label><input name="cost" type="number" step=".01" min="0" required></div></div>`, 'Receive stock',fd=>{let v=Object.fromEntries(fd),m=db.medicines.find(x=>x.id===v.medicine),s=db.suppliers.find(x=>x.id===v.supplier),q=Number(v.qty),batchId=v.batch||'BT-'+String(Date.now()).slice(-4);let batch=m.batches.find(b=>b.id===batchId);if(batch)batch.qty+=q;else m.batches.push({id:batchId,qty:q,expiry:v.expiry,cost:Number(v.cost)});db.purchases.unshift({id:'PO-'+String(Date.now()).slice(-4),date:new Date().toISOString(),supplier:s.name,items:1,total:q*Number(v.cost),status:'Received'});save();toast('Purchase received — inventory updated');render()})}
function userModal(){modal('Add team member',`<div class="form-grid"><div class="field"><label>Full name *</label><input name="name" required></div><div class="field"><label>Email *</label><input name="email" type="email" required></div><div class="field"><label>Role</label><select name="role"><option>Cashier</option><option>Pharmacist</option><option>Admin</option></select></div></div>`,'Add member',fd=>{db.users.push({...Object.fromEntries(fd),status:'Active'});save();render();toast('Team member added')})}
function addCart(id){let m=db.medicines.find(x=>x.id===id);if(!m)return;if(stock(m)<1)return toast('This product is out of stock.',true);let existing=cart.find(x=>x.medicineId===id);if(existing){if(existing.qty>=stock(m))return toast('No more stock available.',true);existing.qty++}else{let batch=[...m.batches].filter(b=>b.qty>0).sort((a,b)=>a.expiry.localeCompare(b.expiry))[0];cart.push({medicineId:id,name:m.name,price:Number(m.price),qty:1,batchId:batch?.id})}query='';render()}
function completeSale(){if(!cart.length)return;let customer=document.querySelector('#customer')?.value.trim()||'Walk-in customer',discount=Number(document.querySelector('#discount')?.value||0),sub=cart.reduce((s,x)=>s+x.qty*x.price,0);if(discount>sub)return toast('Discount cannot exceed subtotal.',true);for(const x of cart){let m=db.medicines.find(z=>z.id===x.medicineId);if(stock(m)<x.qty)return toast(`${m.name}: not enough stock.`,true)}for(const x of cart){let m=db.medicines.find(z=>z.id===x.medicineId),remaining=x.qty;for(const b of [...m.batches].filter(b=>b.qty>0).sort((a,b)=>a.expiry.localeCompare(b.expiry))){let take=Math.min(remaining,b.qty);b.qty-=take;remaining-=take;if(!remaining)break}}let total=sub-discount;db.sales.unshift({id:'INV-'+String(Date.now()).slice(-5),date:new Date().toISOString(),customer,items:structuredClone(cart),total});save();cart=[];toast('Sale completed. Stock has been updated.');setPage('dashboard')}
function exportCsv(){let rows=[['Medicine','Generic','Category','Stock','Unit','Sell price','Reorder level','Next expiry'],...db.medicines.map(m=>[m.name,m.generic,m.category,stock(m),m.unit,m.price,m.reorder,m.batches.map(b=>b.expiry).sort()[0]||''])];let csv=rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='medistore-inventory.csv';a.click();URL.revokeObjectURL(a.href);toast('Inventory CSV exported')}
function printBill(){if(!cart.length)return;let sub=cart.reduce((s,x)=>s+x.qty*x.price,0),customer=document.querySelector('#customer')?.value||'Walk-in customer';let w=window.open('','_blank','width=420,height=650');w.document.write(`<html><head><title>MediStore Invoice</title><style>body{font:14px Arial;padding:25px;color:#18342a}h2{text-align:center}small{color:#607067}table{width:100%;border-collapse:collapse;margin:20px 0}td{border-bottom:1px solid #ddd;padding:9px 2px}.r{text-align:right}</style></head><body><h2>Green Cross Pharmacy</h2><center><small>Nagpur · Tax invoice</small></center><hr><p>Invoice: ${Date.now().toString().slice(-5)}<br>Customer: ${esc(customer)}<br>${dateFmt(new Date())}</p><table>${cart.map(x=>`<tr><td>${esc(x.name)} × ${x.qty}</td><td class="r">${money(x.qty*x.price)}</td></tr>`).join('')}<tr><td><b>Total</b></td><td class="r"><b>${money(sub)}</b></td></tr></table><center><small>Thank you for shopping with us.</small></center><script>window.print()<\/script></body></html>`);w.document.close()}
function bindDynamic(){let search=document.querySelector('#invSearch');if(search)search.oninput=e=>{query=e.target.value;let pos=e.target.selectionStart;render();let s=document.querySelector('#invSearch');s.focus();s.setSelectionRange(pos,pos)};let filter=document.querySelector('#invFilter');if(filter)filter.onchange=e=>{invFilter=e.target.value;render()};let ps=document.querySelector('#productSearch');if(ps){ps.oninput=e=>{query=e.target.value;let q=document.querySelector('#suggestions');let list=db.medicines.filter(m=>`${m.name} ${m.generic} ${m.id}`.toLowerCase().includes(query.toLowerCase())&&query.length>0);q.innerHTML=list.length?list.map(m=>`<button class="suggestion" data-action="add-cart" data-id="${m.id}"><span><b>${esc(m.name)}</b><small>${esc(m.generic)} · ${stock(m)} ${esc(m.unit.toLowerCase())}s available</small></span><strong>${money(m.price)}</strong></button>`).join(''):`<div class="empty">${query?'No matching medicines. Add it to the catalogue first.':'Type to search'}</div>`;q.hidden=!query};ps.onkeydown=e=>{if(e.key==='Escape'){query='';document.querySelector('#suggestions').hidden=true;ps.value=''}};ps.focus()}document.querySelectorAll('[data-qty]').forEach(el=>el.onchange=e=>{let i=Number(e.target.dataset.qty),max=stock(db.medicines.find(m=>m.id===cart[i].medicineId));cart[i].qty=Math.max(1,Math.min(max,Number(e.target.value)||1));render()});document.querySelectorAll('[data-role]').forEach(el=>el.onchange=e=>{db.users[Number(e.target.dataset.role)].role=e.target.value;save();toast('Access role updated')})}
document.querySelector('#nav').addEventListener('click',e=>{let b=e.target.closest('[data-page]');if(b)setPage(b.dataset.page)});
document.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(!b){if(page==='billing'&&!e.target.closest('.bill-search')){let sug=document.querySelector('#suggestions');if(sug)sug.hidden=true}return}let a=b.dataset.action;switch(a){case'go-billing':setPage('billing');break;case'go-inventory':setPage('inventory');break;case'go-reports':setPage('reports');break;case'add-med':medModal();break;case'edit-med':medModal(b.dataset.id);break;case'add-supplier':supplierModal();break;case'new-purchase':purchaseModal(b.dataset.id);break;case'add-user':userModal();break;case'add-cart':addCart(b.dataset.id);break;case'remove-cart':cart.splice(Number(b.dataset.index),1);render();break;case'clear-cart':cart=[];query='';render();toast('Bill cleared');break;case'complete-sale':completeSale();break;case'print-bill':printBill();break;case'export-report':exportCsv();break;case'close-modal':closeModal();break;case'help':modal('Quick help',`<div class="alert-list"><div class="alert-row"><span class="alert-symbol amber-bg">1</span><div class="alert-copy"><b>Create a sale</b><small>Open New sale, type a product name and choose the suggestion.</small></div></div><div class="alert-row"><span class="alert-symbol amber-bg">2</span><div class="alert-copy"><b>Receive a purchase</b><small>Choose New purchase, select supplier, medicine and batch expiry.</small></div></div><div class="alert-row"><span class="alert-symbol amber-bg">3</span><div class="alert-copy"><b>Data storage</b><small>This prototype saves data in this browser on this device.</small></div></div></div>`,'Got it');document.querySelector('.modal-foot .btn.primary').onclick=e=>{e.preventDefault();closeModal()};break;case'profile':modal('Demo access',`<p class="subheading">Choose a role to preview role-based access.</p><div class="field"><select id="demoRole"><option>Admin</option><option>Pharmacist</option><option>Cashier</option></select></div>`,'Apply',()=>{let r=document.querySelector('#demoRole').value;db.role=r;save();document.querySelector('#roleLabel').textContent=r;toast(`Viewing as ${r}`)});break;case'alert':modal('Inventory alerts',`<div class="alert-list">${db.medicines.filter(m=>stock(m)<=m.reorder||nearExpiry(m)).map(m=>`<div class="alert-row"><div class="alert-symbol ${stock(m)<=m.reorder?'red-bg':'amber-bg'}">!</div><div class="alert-copy"><b>${esc(m.name)}</b><small>${stock(m)<=m.reorder?`${stock(m)} units remaining`:'Batch approaching expiry'}</small></div></div>`).join('')||'All clear — no alerts.'}</div>`,'Done');document.querySelector('.modal-foot .btn.primary').onclick=e=>{e.preventDefault();closeModal()};break}});
document.querySelector('#profileBtn').onclick=()=>document.dispatchEvent(new CustomEvent('profile-open'));
document.addEventListener('profile-open',()=>{modal('Demo access',`<p class="subheading">Choose a role to preview role-based access.</p><div class="field"><select id="demoRole">${['Admin','Pharmacist','Cashier'].map(r=>`<option ${db.role===r?'selected':''}>${r}</option>`)}</select></div>`,'Apply',()=>{db.role=document.querySelector('#demoRole').value;save();document.querySelector('#roleLabel').textContent=db.role;toast(`Viewing as ${db.role}`)})});
document.querySelector('#alertBtn').onclick=()=>{let alerts=db.medicines.filter(m=>stock(m)<=m.reorder||nearExpiry(m));modal('Inventory alerts',`<div class="alert-list">${alerts.map(m=>`<div class="alert-row"><div class="alert-symbol ${stock(m)<=m.reorder?'red-bg':'amber-bg'}">!</div><div class="alert-copy"><b>${esc(m.name)}</b><small>${stock(m)<=m.reorder?`${stock(m)} units remaining`:'Batch approaching expiry'}</small></div></div>`).join('')||'<div class="empty">All clear — no alerts.</div>'}</div>`,'Done');document.querySelector('.modal-foot .btn.primary').onclick=e=>{e.preventDefault();closeModal()}};
document.addEventListener('keydown',e=>{if(e.key==='F2'){e.preventDefault();setPage('billing')}if(e.key==='Escape')closeModal()});
document.querySelector('#today').textContent=new Intl.DateTimeFormat('en-IN',{weekday:'short',day:'2-digit',month:'short',year:'numeric'}).format(new Date());document.querySelector('#roleLabel').textContent=db.role==='Admin'?'Store admin':db.role;render();
